[env]
BIN_FOLDER = "./bin"
SPACE_BIN = "${BIN_FOLDER}/space.8xp"
GENERATED_SRC = "./src/generated"

[tasks.build]
command = "mkdir"
args = ["-p", "${BIN_FOLDER}"]

[tasks.space]
command = "fasmg"
args = [
  "src/main.asm",
  "${SPACE_BIN}",
]
dependencies = ["build"]

[tasks.all]
dependencies = ["space"]

[tasks.clean]
command = "rm"
args = ["-rf", "${BIN_FOLDER}"]

[tasks.default]
alias = "all"
