[SpritePlayer]
file = "player.png"

[SpriteDebug]
file = "debug.png"

[SpriteProjectile]
file = "projectile.png"

[SpriteEnemyDeath]
file = "enemy_death.png"

[SpriteEnemy1a]
file = "enemy_1a.png"

[SpriteEnemy1b]
file = "enemy_1b.png"

[SpriteEnemy2a]
file = "enemy_2a.png"

[SpriteEnemy2b]
file = "enemy_2b.png"

[SpriteEnemy3a]
file = "enemy_3a.png"

[SpriteEnemy3b]
file = "enemy_3b.png"
