[player.sprites]
Player = "player.png"
PlayerDeathA = "player_death_a.png"
PlayerDeathB = "player_death_b.png"

[debug.sprites]
Debug = "debug.png"

[projectile.sprites]
Projectile = "projectile.png"

[enemy_death.sprites]
EnemyDeath = "enemy_death.png"

[enemy_1.sprites]
Enemy1a = "enemy_1a.png"
Enemy1b = "enemy_1b.png"

[enemy_2.sprites]
Enemy2a = "enemy_2a.png"
Enemy2b = "enemy_2b.png"

[enemy_3.sprites]
Enemy3a = "enemy_3a.png"
Enemy3b = "enemy_3b.png"

[enemy_4.sprites]
Enemy4 = "enemy_4.png"

[characters.pointer_table]
name = "CharacterTable"

[characters.sprites]
Char0 = "character_0.png"
Char1 = "character_1.png"
Char2 = "character_2.png"
Char3 = "character_3.png"
Char4 = "character_4.png"
Char5 = "character_5.png"
Char6 = "character_6.png"
Char7 = "character_7.png"
Char8 = "character_8.png"
Char9 = "character_9.png"
CharA = "character_a.png"
CharB = "character_b.png"
CharC = "character_c.png"
CharD = "character_d.png"
CharE = "character_e.png"
CharF = "character_f.png"
CharG = "character_g.png"
CharH = "character_h.png"
CharI = "character_i.png"
CharJ = "character_j.png"
CharK = "character_k.png"
CharL = "character_l.png"
CharM = "character_m.png"
CharN = "character_n.png"
CharO = "character_o.png"
CharP = "character_p.png"
CharQ = "character_q.png"
CharR = "character_r.png"
CharS = "character_s.png"
CharT = "character_t.png"
CharU = "character_u.png"
CharV = "character_v.png"
CharW = "character_w.png"
CharX = "character_x.png"
CharY = "character_y.png"
CharZ = "character_z.png"

[shield_1.sprites]
Shield1_0 = "shield_1_0.png"
Shield1_1 = "shield_1_1.png"
Shield1_3 = "shield_1_3.png"
Shield1_4 = "shield_1_4.png"

[shield_2.sprites]
Shield2_0 = "shield_2_0.png"
Shield2_1 = "shield_2_1.png"
Shield2_2 = "shield_2_2.png"
Shield2_3 = "shield_2_3.png"
Shield2_4 = "shield_2_4.png"

[shield_3.sprites]
Shield3_0 = "shield_3_0.png"
Shield3_1 = "shield_3_1.png"
Shield3_2 = "shield_3_2.png"
Shield3_3 = "shield_3_3.png"
Shield3_4 = "shield_3_4.png"

[shield_4.sprites]
Shield4_0 = "shield_4_0.png"
Shield4_1 = "shield_4_1.png"
Shield4_2 = "shield_4_2.png"
Shield4_3 = "shield_4_3.png"
Shield4_4 = "shield_4_4.png"
